name: test
channels:
        - conda-forge
        - bioconda
dependencies:
        - matplotlib
        - pandas
        - jupyterlab_widgets
        - ipywidgets
        - ipykernel 
        - jupyterlab

        - pip
        - pip:
          - wheel
          - setuptools
          - twine
          - pytest==4.4.1
          - pytest-runner==4.4



#conda install -c conda-forge ipympl ## for jupyter

