name: devbio
channels:
        - conda-forge
        - bioconda
dependencies:

        - jupyterlab_widgets
        - ipywidgets
        - ipykernel 
        - jupyterlab
        - python=3.9

        - matplotlib
        - pandas
        - numpy
        - numba
        - scipy
        - seaborn

        - devbio-napari
        - "dask[array]"
        - "dask[distributed]"
        - joblib
        - napari-workflows

        - scikit-image
        - pyclesperanto-prototype

#conda install -c conda-forge ipympl ## for jupyter

